name: example
description: Locy Example App
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  localization:
    path: ./localization
  easiest_localization:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/

easiest_localization:
  # By default - is empty / null
  excluded:
    - localizely_example
  # Default name of output class
  class_name: LocalizationMessages
  # Default description of generated package
  description: Some description for generated package
  # Default name of generated package
  package_name: localization
  # Default path to generated package - the root of your project, under which will be created folder <package_name> (localization - by default)
  package_path: ./
  # Default version of generated package
  package_version: 1.0.0
  # Only one requirement applies to that regexp - it should contain one named argument <lang>
  # Like ".*translation.*(?<lang>[A-Za-z]{2})" will match on any json / yaml file under any folder with substring "translation", or if file will contain that substring
  reg_exp: "(?<lang>[A-Za-z]{2})_?(?<country>[A-Z]{2})?_?(?<pattern>intl)?.(ya?ml|json)$"
  # Will run "dart fix --apply" to generated package to make it perfect, but consumes a lot of time (100ms - without and about 5-7 seconds with it)
  format_output: false
  easiest_localization_version: "\n    path: ../../"
